CREATE TABLE `zfwx_wxuser_site_indexcontent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(45) NOT NULL,
  `content_html` TEXT NULL,
  `content_menu1_title` VARCHAR(45) NULL,
  `content_menu1_item1_text` VARCHAR(45) NULL,
  `content_menu1_item1_link` VARCHAR(255) NULL,
  `content_menu1_item2_text` VARCHAR(45) NULL,
  `content_menu1_item2_link` VARCHAR(255) NULL,
  `content_menu1_item3_text` VARCHAR(45) NULL,
  `content_menu1_item3_link` VARCHAR(255) NULL,
  `content_menu1_item4_text` VARCHAR(45) NULL,
  `content_menu1_item4_link` VARCHAR(255) NULL,
  `content_menu1_item5_text` VARCHAR(45) NULL,
  `content_menu1_item5_link` VARCHAR(255) NULL,
  `content_menu1_item6_text` VARCHAR(45) NULL,
  `content_menu1_item6_link` VARCHAR(255) NULL,
  `content_menu2_title` VARCHAR(45) NULL,
  `content_menu2_item1_text` VARCHAR(45) NULL,
  `content_menu2_item1_link` VARCHAR(255) NULL,
  `content_menu2_item2_text` VARCHAR(45) NULL,
  `content_menu2_item2_link` VARCHAR(255) NULL,
  `content_menu2_item3_text` VARCHAR(45) NULL,
  `content_menu2_item3_link` VARCHAR(255) NULL,
  `content_menu2_item4_text` VARCHAR(45) NULL,
  `content_menu2_item4_link` VARCHAR(255) NULL,
  `content_menu2_item5_text` VARCHAR(45) NULL,
  `content_menu2_item5_link` VARCHAR(255) NULL,
  `content_menu2_item6_text` VARCHAR(45) NULL,
  `content_menu2_item6_link` VARCHAR(255) NULL,
  `content_goodslist1_ids` VARCHAR(255) NULL,
  `content_goodslist2_ids` VARCHAR(255) NULL,
  `content_goodslist3_ids` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC));